### ISSUE TITLE
Application created from RactJS template fails building

### ISSUE THREAD

**Issue by alexeyzimarev** [ServiceStack/ServiceStackVS#15]
I get this error when trying to create a new application using the ReactJS template. I have the latest GA plugin version.

Failed to run "c:\dev\ReactApp1\ReactApp1\ReactApp1\Gruntfile.js"...
cmd.exe /c grunt -b "c:\dev\ReactApp1\ReactApp1\ReactApp1" --gruntfile "c:\dev\ReactApp1\ReactApp1\ReactApp1\Gruntfile.js" --tasks "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\TaskRunnerExplorer\Scripts" vs-grunt-task-reader
module.js:340
    throw err;
          ^
Error: Cannot find module './lexer'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\dev\ReactApp1\ReactApp1\ReactApp1\node_modules\grunt\node_modules\coffee-script\lib\coffee-script\coffee-script.js:10:10)
    at Object.<anonymous> (c:\dev\ReactApp1\ReactApp1\ReactApp1\node_modules\grunt\node_modules\coffee-script\lib\coffee-script\coffee-script.js:167:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by Layoric** [comment]
Could you provide some more details? 

Where are you seeming this error? 
What version of Visual Studio are you using? 
What version of NodeJS are you running?
What command did you try when you got this error?

The error you show could be a result of `npm install` not finished yet when a command is run. You can try performing `npm install` again to ensure all your NPM dependencies are correctly installed. If not, try clearing your `node_modules` directory first before the install.

Also not sure what you mean by the "GA Plugin", is that another Visual Studio extension you are using along with ServiceStackVS?

**Comment by alexeyzimarev** [comment]
I am seeing this error in the Npm output window in Visual Studio
I am using VS 2015 Professional
Node v0.12.2
I have not tried any command. The output is shown when I create a ReactJS project from the ServiceStack templates section

By "GA" I mean the generally available plugin version that I installed today from the Visual Studio gallery, not a self-compiled dev version from github, for example.

**Comment by Layoric** [comment]
The issue seems to be caused by the VS 2015 Task runner trying to evaluate the Gruntfile.js before the NPM install has completed. The project template doesn't wait for NPM install to finish and lets it's continue in the background while the other projects are being created as since the Grunt tasks aren't used for the development workflow, they don't need to be ready to start being productive with the template building your application. 

You can safely ignore this output from the Task Runner output window (Unless you have another output window showing this error?), when you go to use the Task runner, use the refresh button at the top left to show all the tasks successfully.

![image](https://cloud.githubusercontent.com/assets/234642/10933139/6d348396-832a-11e5-8007-4e9c26f229fc.png)

I'll investigate how this output from the Task runner might be avoided.

Thanks!

**Comment by Layoric** [comment]
@alexeyzimarev I've updated ServiceStackVS to let VS 2015 handle NPM and Bower Install, this seems to automatically prompt Task Runner to refresh once NPM and Bower have completed.

Latest version is [available here](https://s3.amazonaws.com/ci-dist/ssvs/latest/ServiceStackVS.vsix), could you update the extension and let me know if this resolves your issue?

**Comment by alexeyzimarev** [comment]
@Layoric Yes, this version has managed to create a new React project without any error, thanks!

**Comment by Layoric** [comment]
Good to hear, thanks for reporting the issue! :+1:

**Comment by Layoric** [comment]
@alexeyzimarev if you're having any issues with the React Desktop Apps template in the pre-release ServiceStackVS you have installed, you can use the same link above to get the latest again. You will have to manually uninstall/reinstall due to same version number. There are a couple of fixes I've pushed since this issue was opened so thought you should be aware. Cheers!
