### ISSUE TITLE
ServiceStackXS Add-In for Xamarin 5.10 does not install (missing dependencies)

### ISSUE THREAD

**Issue by DJFliX** [ServiceStack/ServiceStackVS#19]
When installing ServiceStackXS add-in I get the message about the following dependencies:
`Missing: ServiceStackXS.Core v5.0`
`Missing: ServiceStackXS.Ide v5.0`

I can not find anything on the interwebs about these packages and I can not seem to find them in the repositories. Is there something wrong in the builds?

**Comment by Layoric** [comment]
Just to clarify some details. You're using Xamarin Studio 5.1 and not the more recent 5.10? Also, which operating system are you running it on?

Could you also confirm channel you got the extension from? Beta, stable? Thanks.

**Comment by DJFliX** [comment]
Sorry, I meant 5.10 (sorry about that!). I can only see the package on the beta channel. I'm running OS X 10.11.1.

**Comment by Layoric** [comment]
No worries, it's hard to avoid Xamarin Studio updates, hence why I thought I'd ask :)

And you're right that there seems to only be the beta channel listing an available package. There use to use a 0.1 version in Stable but it's no longer there, and the addin.monodevelop.com gallery build server fails to build the original tag that it came from. I have been trying for most of a day to get ServiceStackXS available from the Xamarin Studio Gallery without success.

I've built a new version locally to get to going until this issue is resolved with the addin build server/publish process. You'll have to [download it from here](https://github.com/ServiceStack/ServiceStackVS/raw/master/src/ServiceStackXS/ServiceStackXS.ServiceStack.ServiceStackXS_0.3.mpack) and using the [install from file](https://github.com/ServiceStack/ServiceStack/wiki/CSharp-Add-ServiceStack-Reference#install-from-file) method to install it.

I've tested it on Windows 8.1 + XS 5.10 and OSX 10.11 + XS 5.10 and both worked for me for this copy but let me know if you have any problems and I'll update this issue once a new working version is available from the Xamarin Studio gallery.

**Comment by DJFliX** [comment]
I can verify that this local build you created works for me, thanks for providing me with that! I'll await any updates on the issue :+1:

**Comment by Layoric** [comment]
I've upped the version of the addin and it's available via the **Alpha channel**. I've confirmed this works too on OSX 10.11 + XS 5.10. Still trying having trouble with 5.9 on another PC. Once I had that sorted I'll updated the beta channel to 0.3 and let you know. Folks on the Xamarin Forums are helping me understand the problem so hopefully should be able to get updating/installing SSXS from Xamarin Studio itself soon enough. :+1:

**Comment by Layoric** [comment]
New version (0.3) of ServiceStackXS now pushed out to the Beta and Stable channel replacing the broken version 0.2 and 0.1 versions. Issues with addins.monodevelop.com build server and related to versions of Mono.Posix. Removed local dependency on Mono.Posix which came from GTK generated code. 

Tested on:
Windows 8.1 + Xamarin Studio 5.10
Windows 7  + Xamarin Studio 5.10
OSX 10.11 + Xamarin Studio 5.10
Ubuntu 15.04 + MonoDevelop 5.10
