### ISSUE TITLE
ssutil does not work for concrete typescript types

### ISSUE THREAD

**Issue by MortenChristiansen** [ServiceStack/ServiceStackVS#43]
I'm trying to update a file called `api.dtos.ts` but I get the error `Failed to complete operation. Update file path provided does not have a valid ServiceStack reference extension.`.

The executed command is `"../tools/ServiceStack Add Service Reference/ssutil.exe" ../src/UVDomainLanguage.Web/App/api.dtos.ts` but it works fine if I change the name of the file to `api.dtos.d.ts` and update the command accordingly.

Am I using the tool incorrectly?

**Comment by Layoric** [comment]
You were using it correctly, but the ssutil in `dist` had not been updated since Typescript supported both.

I've updated it to 1.1.1 and [cut a new built which includes the support](https://github.com/ServiceStack/ServiceStackVS/raw/master/dist/ssutil.exe) for the command you are trying to run above. Let me know if you have any issues. 👍

**Comment by MortenChristiansen** [comment]
Thanks, that worked much better :)
